version: '3.9'

services:
  vogeb-solidity:
    # 使用 Dockerfile 构建镜像
    # Build the image using Dockerfile
    build:
      context: . # 使用当前目录的 Dockerfile
      # Use the Dockerfile in the current directory
    container_name: vogeb-solidity
    ports:
      - "3000:80"  # 将容器的 80 端口映射到宿主机的 80 端口
      # Map container port 80 to host port 80
    restart: always
    environment:
      - NODE_ENV=production
